services:
  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    container_name: wayfinder-valhalla
    restart: unless-stopped
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - ./data/valhalla:/custom_files
    environment:
      tile_urls: ""
      server_threads: 2
      serve_tiles: "True"
      use_tiles_ignore_pbf: "True"
      tileset_name: valhalla_tiles
      build_elevation: "False"
      build_admins: "False"
      build_time_zones: "False"
      build_transit: "False"
      build_tar: "True"
      force_rebuild: "False"
      update_existing_config: "True"
