"use client";
import { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
import CalendarImport from './CalendarImport';
import PlaceSearch from './PlaceSearch';
import PreferenceQuestions from './PreferenceQuestions';
import { ARJUN } from '../../lib/routing.mjs';
export default function Settings({ open,onClose,profile,setProfile,prefs,setPrefs,layers,setLayers,onCalendarSelect,events,onEvents,home,setHome,work,setWork,routine,setRoutine,onOnboarding,demo,setDemo,onDemo,notificationBusy,notificationStatus,onNotifications,onDisableNotifications }) {
  const dialog=useRef(null);
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  return <dialog ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose();}} aria-labelledby="settings-title" className="m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-[488px] overflow-y-auto rounded-3xl bg-cream p-5 text-ink backdrop:bg-black/40">
    <div className="mb-5 flex items-center justify-between"><h2 id="settings-title" className="text-xl font-bold">Settings</h2><button autoFocus type="button" aria-label="Close settings" onClick={onClose} className="flex min-h-11 min-w-11 items-center justify-center rounded-xl bg-white"><X size={20}/></button></div>
    <button type="button" onClick={()=>{onClose();onOnboarding();}} className="mb-4 min-h-12 w-full rounded-xl bg-ink text-sm font-bold text-white">Start onboarding</button>
    <section className="mb-4 rounded-2xl bg-white p-4" aria-label="Saved places"><h3 className="mb-3 text-sm font-bold">Home & work</h3><PlaceSearch label="Home" value={home} onChange={setHome}/><div className="mt-3"><PlaceSearch label="Work" value={work} onChange={setWork}/></div></section>
    <details className="mb-4 rounded-2xl bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-bold">Travel preferences</summary><div className="mb-4 grid grid-cols-2 gap-2">{['arjun','custom'].map(p=><button type="button" key={p} aria-pressed={profile===p} onClick={()=>{setProfile(p);if(p==='arjun')setPrefs(ARJUN);}} className={'min-h-11 rounded-xl text-sm font-bold '+(profile===p?'bg-ink text-white':'bg-cream')}>{p==='arjun'?'Arjun':'Custom'}</button>)}</div><PreferenceQuestions prefs={prefs} onChange={v=>{setProfile('custom');setPrefs(v);}}/><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Leave home<input aria-label="Leave home" type="time" value={routine.leaveHome} onChange={e=>setRoutine({...routine,leaveHome:e.target.value})} className="mt-2 min-h-12 w-full rounded-xl border border-fog bg-cream p-2"/></label><label className="text-xs font-bold">Head home<input aria-label="Head home" type="time" value={routine.leaveWork} onChange={e=>setRoutine({...routine,leaveWork:e.target.value})} className="mt-2 min-h-12 w-full rounded-xl border border-fog bg-cream p-2"/></label></div></details>
    <CalendarImport events={events} onEvents={onEvents} onSelect={item=>{onCalendarSelect(item);if(item)onClose();}}/>
    <section className="my-4 rounded-2xl bg-white p-4"><h3 className="text-sm font-bold">Detour notifications</h3><p role="status" className="mt-2 text-xs text-moss">{notificationStatus || 'Get a preferred detour when rain, disruption or crowding changes your commute.'}</p><p className="mt-2 text-xs text-moss">Enabling this stores commute times and locations on this app’s server for background checks. Event titles stay on your device.</p><button type="button" onClick={onNotifications} disabled={notificationBusy} className="mt-2 min-h-12 w-full rounded-xl bg-fog text-sm font-bold">{notificationBusy?'Connecting…':'Enable detour notifications'}</button><button type="button" onClick={onDisableNotifications} disabled={notificationBusy} className="min-h-11 w-full text-sm text-moss">Turn notifications off</button></section>
    <label className="my-4 flex min-h-14 items-center justify-between rounded-2xl bg-white px-4 text-sm font-bold">Local map layers<input type="checkbox" checked={layers} onChange={e=>setLayers(e.target.checked)} className="h-6 w-6 accent-moss"/></label>
    <details className="rounded-2xl bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-bold">Try Arjun’s commute</summary><p className="mb-3 text-xs text-moss">824654 → Fusionopolis. Simulated conditions; real mapped routes. Home and work settings are unchanged.</p><label className="flex min-h-12 items-center justify-between text-sm">Wet weather<input type="checkbox" checked={demo.rain} onChange={e=>setDemo({...demo,rain:e.target.checked})} className="h-5 w-5 accent-moss"/></label><label className="flex min-h-12 items-center justify-between text-sm">Punggol LRT disruption<input type="checkbox" checked={demo.disruption} onChange={e=>setDemo({...demo,disruption:e.target.checked})} className="h-5 w-5 accent-moss"/></label><button type="button" onClick={()=>{onDemo();onClose();}} className="mt-2 min-h-12 w-full rounded-xl bg-ink text-sm font-bold text-white">{demo.rain||demo.disruption?'Run demo':'Exit demo'}</button></details>
    <button type="button" onClick={onClose} className="mt-4 min-h-12 w-full rounded-2xl bg-ink text-sm font-bold text-white">Done</button>
  </dialog>;
}
